<a href="https://colab.research.google.com/github/NishmthaM/mathe_using_python/blob/main/mathe_in_python_lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
np.set_printoptions(suppress=True)

Scalar,Vector,Matrix and Tensor in numpy

In [5]:
#scalar- single number
scalar = 5.0
print(scalar)
print("Type of scalar:", type(scalar))

5.0
Type of scalar: <class 'float'>


In [6]:
#vector - 1D data

vector = np.array([5,8,6])
print("Type of vector:",type(vector))
print("vector:",vector)
print("Shape of the vector:",vector.shape)

Type of vector: <class 'numpy.ndarray'>
vector: [5 8 6]
Shape of the vector: (3,)


In [7]:
#matrix -2D data

matrix = np.array(
    [
      [2,6,4],
      [1,3,5]
    ])
print("Type of matrix:",type(matrix))
print("matrix:",matrix)
print("Shape of the matrix:",matrix.shape)

Type of matrix: <class 'numpy.ndarray'>
matrix: [[2 6 4]
 [1 3 5]]
Shape of the matrix: (2, 3)


In [8]:
#Tensor - more than 2D data

tensor = np.array(
    [[[
      [2,6,4],
      [1,3,5]
    ],
    [
        [2.6, 3.6, 2.8],
        [1.1, 3.1, 2.2]
    ],

    [
        [1, 6, 5],
        [6, 8, 6]
    ]
      ]])
print("Type of tensor:",type(tensor))
print("tensor:",tensor)
print("Shape of the tensor:",tensor.shape)
print(tensor.ndim)

Type of tensor: <class 'numpy.ndarray'>
tensor: [[[[2.  6.  4. ]
   [1.  3.  5. ]]

  [[2.6 3.6 2.8]
   [1.1 3.1 2.2]]

  [[1.  6.  5. ]
   [6.  8.  6. ]]]]
Shape of the tensor: (1, 3, 2, 3)
4


Creating vector and matrices for ml related data  

In [9]:
# feature 1: hours studied
# feature 2: number of practice questions
# target : pass{1} / fail{0}


x1 = np.array(
    [
        [2,30],   # sample 1
        [3,50],   # sample 2
        [1,20]    # sample 3
    ]
)


y1=np.array([0, 1, 0])

print("Input data matrix X:\n", x1)
print("X shape:", x1.shape)   # (n_samples , n_features)

print("-------")

print("Output vector y:\n", y1)
print("Y shape:", y1.shape)   # (n_samples)


# A single sample as a vector
x2 = x1[0]
print("\nFirst sample as a vector:", x2)
print("x2 shape:", x2.shape)


Input data matrix X:
 [[ 2 30]
 [ 3 50]
 [ 1 20]]
X shape: (3, 2)
-------
Output vector y:
 [0 1 0]
Y shape: (3,)

First sample as a vector: [ 2 30]
x2 shape: (2,)


Basic operations: addition, scalar multiplication,transpose


In [10]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array ([[2,6,4],
      [1,3,5]])
print("a:", a)
print("b:", b)

print("")

add= a+b
print("vector addition :",add)

print("")

# scaling up
scalar= 2*a
print("Scalar multiplication 2*a :",scalar)

# scaling down

scalar1=0.5 * a
print("Scalar multiplication 0.5*a",scalar1)

print("")

#transpose

trans=c.T
print("Transpose of matrix",trans)
print("Shape of transpose matrix:",trans.shape,"| Shape of matrix",c.shape)

a: [1 2 3]
b: [4 5 6]

vector addition : [5 7 9]

Scalar multiplication 2*a : [2 4 6]
Scalar multiplication 0.5*a [0.5 1.  1.5]

Transpose of matrix [[2 1]
 [6 3]
 [4 5]]
Shape of transpose matrix: (3, 2) | Shape of matrix (2, 3)


In [11]:
import numpy as np

In [12]:
np.set_printoptions(suppress=True)

Dot product


In [13]:
v1=np.array([2,3,6])
v2=np.array([4,2,7])

print("V1:",v1)
print("V2:",v2)



V1: [2 3 6]
V2: [4 2 7]


In [14]:
dot=np.dot(v1,v2)
print("Dot product v1.v2:",dot)

Dot product v1.v2: 56


Euclidean distance

In [15]:
diff= v1-v2
print("Diffrence v1-v2:",diff)

Diffrence v1-v2: [-2  1 -1]


In [16]:
distance=np.linalg.norm(diff)
print("Euclidians distance :",distance)

Euclidians distance : 2.449489742783178


Matrix multiplication linear model

In [19]:
X= np.array([
    [0.2, 0.3],
    [0.6, 0.4],
    [0.5, 0.7]
])

print("X:\n",X)
print("X shape:", X.shape)



X:
 [[0.2 0.3]
 [0.6 0.4]
 [0.5 0.7]]
X shape: (3, 2)


In [20]:
w=np.array([
    [0.5],
    [0.6]
])
print("w:\n",w)
print("w shape:", w.shape)

w:
 [[0.5]
 [0.6]]
w shape: (2, 1)


In [22]:
Xw= X @ w # np.dot
print("Xw:\n",Xw)
print("Xw shape:", Xw.shape)

Xw:
 [[0.28]
 [0.54]
 [0.67]]
Xw shape: (3, 1)
