<a href="https://colab.research.google.com/github/NishmthaM/mathe_using_python/blob/main/mathe_in_python_lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True)

Scalar,Vector,Matrix and Tensor in numpy

In [4]:
#scalar- single number
scalar = 5.0
print(scalar)
print("Type of scalar:", type(scalar))

5.0
Type of scalar: <class 'float'>


In [5]:
#vector - 1D data

vector = np.array([5,8,6])
print("Type of vector:",type(vector))
print("vector:",vector)
print("Shape of the vector:",vector.shape)

Type of vector: <class 'numpy.ndarray'>
vector: [5 8 6]
Shape of the vector: (3,)


In [6]:
#matrix -2D data

matrix = np.array(
    [
      [2,6,4],
      [1,3,5]
    ])
print("Type of matrix:",type(matrix))
print("matrix:",matrix)
print("Shape of the matrix:",matrix.shape)

Type of matrix: <class 'numpy.ndarray'>
matrix: [[2 6 4]
 [1 3 5]]
Shape of the matrix: (2, 3)


In [12]:
#Tensor - more than 2D data

tensor = np.array(
    [[[
      [2,6,4],
      [1,3,5]
    ],
    [
        [2.6, 3.6, 2.8],
        [1.1, 3.1, 2.2]
    ],

    [
        [1, 6, 5],
        [6, 8, 6]
    ]
      ]])
print("Type of tensor:",type(tensor))
print("tensor:",tensor)
print("Shape of the tensor:",tensor.shape)
print(tensor.ndim)

Type of tensor: <class 'numpy.ndarray'>
tensor: [[[[2.  6.  4. ]
   [1.  3.  5. ]]

  [[2.6 3.6 2.8]
   [1.1 3.1 2.2]]

  [[1.  6.  5. ]
   [6.  8.  6. ]]]]
Shape of the tensor: (1, 3, 2, 3)
4
