<a href="https://colab.research.google.com/github/NishmthaM/mathe_using_python/blob/main/mathe_in_python_lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
np.set_printoptions(suppress=True)

Scalar,Vector,Matrix and Tensor in numpy

In [5]:
#scalar- single number
scalar = 5.0
print(scalar)
print("Type of scalar:", type(scalar))

5.0
Type of scalar: <class 'float'>


In [6]:
#vector - 1D data

vector = np.array([5,8,6])
print("Type of vector:",type(vector))
print("vector:",vector)
print("Shape of the vector:",vector.shape)

Type of vector: <class 'numpy.ndarray'>
vector: [5 8 6]
Shape of the vector: (3,)


In [7]:
#matrix -2D data

matrix = np.array(
    [
      [2,6,4],
      [1,3,5]
    ])
print("Type of matrix:",type(matrix))
print("matrix:",matrix)
print("Shape of the matrix:",matrix.shape)

Type of matrix: <class 'numpy.ndarray'>
matrix: [[2 6 4]
 [1 3 5]]
Shape of the matrix: (2, 3)


In [8]:
#Tensor - more than 2D data

tensor = np.array(
    [[[
      [2,6,4],
      [1,3,5]
    ],
    [
        [2.6, 3.6, 2.8],
        [1.1, 3.1, 2.2]
    ],

    [
        [1, 6, 5],
        [6, 8, 6]
    ]
      ]])
print("Type of tensor:",type(tensor))
print("tensor:",tensor)
print("Shape of the tensor:",tensor.shape)
print(tensor.ndim)

Type of tensor: <class 'numpy.ndarray'>
tensor: [[[[2.  6.  4. ]
   [1.  3.  5. ]]

  [[2.6 3.6 2.8]
   [1.1 3.1 2.2]]

  [[1.  6.  5. ]
   [6.  8.  6. ]]]]
Shape of the tensor: (1, 3, 2, 3)
4


Creating vector and matrices for ml related data  

In [11]:
# feature 1: hours studied
# feature 2: number of practice questions
# target : pass{1} / fail{0}


x1 = np.array(
    [
        [2,30],   # sample 1
        [3,50],   # sample 2
        [1,20]    # sample 3
    ]
)


y1=np.array([0, 1, 0])

print("Input data matrix X:\n", x1)
print("X shape:", x1.shape)   # (n_samples , n_features)

print("-------")

print("Output vector y:\n", y1)
print("Y shape:", y1.shape)   # (n_samples)


# A single sample as a vector
x2 = x1[0]
print("\nFirst sample as a vector:", x2)
print("x2 shape:", x2.shape)


Input data matrix X:
 [[ 2 30]
 [ 3 50]
 [ 1 20]]
X shape: (3, 2)
-------
Output vector y:
 [0 1 0]
Y shape: (3,)

First sample as a vector: [ 2 30]
x2 shape: (2,)
